### ISSUE TITLE
Schedulle commands don't work

### ISSUE THREAD

**Issue by Slagof** [Davoleo/curse-updates#18]
### General Information
 When i try to add a project, or to set the channel or the announcement message it doesn't work

**Describe the bug:**
 When you try to use any of the commands of the category "Schedule" they don't work, the bot doesn't say anything (and the bot is working, it responds to the ||ping comand)

**To Reproduce:**

1. Invite the bot to your server
2. Try any commands of the "General" category (They'll work) (The default prefix is ||)
3. Then try any commands of the "Schedule" category (They will not work)

**Expected behavior:**
 I expected that the commands worked so i can set my project to be in the scheduled check so people can saw the mod updates

**Logs (if available)**<br>
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

***

### Additional Information
**Screenshots (if available):**

![image](https://user-images.githubusercontent.com/70154066/124845222-3c84ec80-df64-11eb-923a-058fff90be05.png)

**Comment by Davoleo** [comment]
You need to prepend the category name if the command is not in the general category, that detail is not documented in any of the embeds
I'll close this thread once I fix this issue, sorry for the inconvenience!
E.G: `||schedule add` or `||schedule show`

**Comment by Slagof** [comment]
It worked. Thanks!
