### ISSUE TITLE
Cannot add Project to schedule

### ISSUE THREAD

**Issue by Charismara** [Davoleo/curse-updates#23]
### General Information

**Describe the bug:**

I get an error when running the `schedule add` command

**To Reproduce:**

1. install the bot
2. run the command
3. error

**Expected behavior:**

Working?
**Logs (if available)**<br>
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

***

### Additional Information
**Screenshots (if available):**

![image](https://user-images.githubusercontent.com/14293974/180656352-c0e9b2be-7ec5-4950-8074-b7312abd217d.png)

**Comment by Davoleo** [comment]
Yeah the old API was dismissed, which broke all standalone versions of the legacy bot, I hope I can get the new version out before this autumn
