### ISSUE TITLE
WARNING: Error during permission evaluation: TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by czmenz** [Davoleo/curse-updates#26]
WARNING: Error during permission evaluation: TypeError: fields.flat is not a function

**Comment by Davoleo** [comment]
the version of the source code currently on the `master` branch is severely outdated so that might be one of the reasons it's failing, I'm currently working on a rewrite (#22), if you want to test the bot, you should try selfhosting the version on branch `v1`

**Comment by czmenz** [comment]
Hello, can you add me on Discord: czmenz, i would need a help with installation on the V1

**Comment by Davoleo** [comment]
@czmenz sorry for the late response, there's a [discord server](http://discord.davoleo.net) dedicated for further support on installation, can you please ask there?
so in case other users have similar issues to yours they can refer to the same chat log.
