### ISSUE TITLE
/updates commands failure crash the bot

### ISSUE THREAD

**Issue by ArcaneLegend1** [Davoleo/curse-updates#27]
### General Information

**Describe the bug:**

**To Reproduce:**

1. First Step
2. First Step
3. First Step

**Expected behavior:**

**Logs (if available)**<br>
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

***

### Additional Information
**Screenshots (if available):**

**Comment by Davoleo** [comment]
I suppose this happened on the version that is currently on the VPS, not sure what you mean by "keeps shutting off" it crashed just one time today at 10AM UTC+1.
can you tell me what your server is? (id or name are both okay), it's likely an issue with corrupt data and I need that info to understand the underlying issue
(also keep in mind i just released 1.0.0 some days ago after some years of dev time, so it's normal for it to be a bit unstable, this should hopefully be better after the first period)
